{% set data = load_setup_py_data() %}

package:
  name: "basictools"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../.

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  entry_points:
    - "MeshFileConvert = BasicTools.IO.MeshFileConverter:Main"

  skip_compile_pyc:
    "BasicToolsParaViewBridge.py"

  script_env:
    - BASICTOOLS_DISABLE_MKL
    - BASICTOOLS_USE_EIGENCYEIGEN

requirements:
  build:
    - python=3.8
    - numpy
    - setuptools-scm
    - conda-forge-pinning-feedstock
  run:
    - python
    - pyparsing
    - numpy
    - scipy
    - sympy
    - scikit-learn

test:
  requires:
    - coverage
    - h5py
    - pyvista
    - meshio
    - vtk
  imports:
     -  BasicTools
  commands :
    - python -u -m BasicTools.Helpers.Tests -k Catalyst -k NativeIntegration -k NativeNumericalWeakForm

about:
    home: {{ data['url'] }}
    license: {{ data['license'] }}
    license_file: LICENSE.txt
    license_family: BSD
    summary: {{ data['description'] }}
    description: {{ data['long_description'] }}

extra:
  recipe-maintainers:
    - felipebordeu
