variables:
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'BasicTools'

stages:
    - doc
    - build
    - test


doc:
    stage: doc
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl zset
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - mkdir public
        - cd docs
        - make html
        - mv _build/html ../public/doc
    artifacts:
        name: "Documentation"
        paths:
            - public/doc



build:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/setup.py build_ext --inplace
    artifacts:
        paths:
          - FE/*.so


test:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT}

testFull:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f -s
    when: manual

coverage:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - export PYTHONPATH=$PWD/../:$PYTHONPATH
        - mkdir -p public/coverage
        - cd public/coverage
        - python ../../Helpers/Tests.py -e ${MYPROJECT} -cl
        - pwd
        - dir
        - cd ../..
        - dir
        - cd public
        - dir
        - cd coverage
        - dir
    artifacts:
        name: "Coverage"
        paths:
            - public/coverage
