variables:
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'BasicTools'

stages:
    - doc
    - build
    - test
    - debug
    - deploy


doc:
    stage: doc
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl zset
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - mkdir public
        - cd docs
        - make html
        - mv _build/html ../public/doc
    artifacts:
        name: "Documentation"
        paths:
            - public/doc



build:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/setup.py build_ext --inplace
    artifacts:
        paths:
          - FE/*.so


test_with_coverage:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - export PYTHONPATH=$PWD/../:$PYTHONPATH
        - mkdir -p public/coverage
        - cd public/coverage
        - python ../../Helpers/Tests.py -e ${MYPROJECT} -cl
    artifacts:
        name: "Coverage"
        paths:
            - public/coverage

test_full_output_stop_at_first_error:
    stage: debug
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f -s
    when: on_failure
    dependencies: [test_with_coverage]



pages:
    stage: deploy
    tags:
        - MSBasicTools
    script:
        - pwd
    artifacts:
        name: "WebSite"
        paths:
            - public