variables:
    MYPROJECT : 'BasicTools'

stages:
    - build
    - doc
    - test
    - debug
    - deploy


doc:
    stage: doc
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - export PYTHONPATH=$PWD/src:$PYTHONPATH
        - python setup.py build_sphinx
        - mkdir public
        - mv docs/_build/html public/doc
    artifacts:
        name: "Documentation"
        paths:
          - public/doc

build_Python3:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - export PYTHONPATH=$PWD/src:$PYTHONPATH
        - python setup.py build_clib
        - python setup.py build_ext --inplace
    artifacts:
        paths:
          - src/BasicTools/FE/*/*36*.so*
          - src/BasicTools/Linalg/*36*.so*
          - src/libCppBasicTools.so

        expire_in: 600 minutes

test_with_pytest_and_coverage:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/src
        - export ABAQUS_NO_FAIL="True"
        - export ZSET_NO_FAIL="True"
        - export CATALYST_NO_FAIL="True"
        - mkdir -p public/coverage
        - pytest --cov=BasicTools --cov-report=html:public/coverage --ignore=src/BasicTools/IO/ParaViewBridge --ignore=src/BasicTools/IO/Wormhole.py src
    coverage: '/pc_cov">([0-9]+\.?[0-9]+?%)/'
    artifacts:
        name: "Coverage"
        paths:
            - public/coverage

test_with_coverage_Python3:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - export ZSET_NO_FAIL="True"
        - export CATALYST_NO_FAIL="True"
        - export PYTHONPATH=$PWD/src:$PYTHONPATH
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/src
        - mkdir -p public/coverage3
        - cd public/coverage3
        - python ../../src/BasicTools/Helpers/Tests.py -e ${MYPROJECT} -cl
        - grep pc_cov index.html
    coverage: '/pc_cov">([0-9]+\.?[0-9]+?%)/'
    artifacts:
        name: "Coverage3"
        paths:
            - public/coverage3

test_full_output_stop_at_first_error_Python3:
    stage: debug
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - export ZSET_NO_FAIL="True"
        - export CATALYST_NO_FAIL="True"
        - export PYTHONPATH=$PWD/src:$PYTHONPATH
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/src
        - python src/BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f -s
    when: on_failure
    dependencies: [test_with_coverage_Python3]

pages:
    stage: deploy
    tags:
        - MSBasicTools
    script:
        - env
        - $LaunchExternalPipelinesScript
    artifacts:
        name: "WebSite"
        paths:
            - public
    only:
        - master