variables:
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'BasicTools'

stages:
    - doc
    - build
    - test
    - debug
    - deploy


doc:
    stage: doc
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl zset
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - mkdir public
        - cd docs
        - make html
        - mv _build/html ../public/doc
    artifacts:
        name: "Documentation"
        paths:
            - public/doc



build_Python2:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/setup.py build_ext --inplace
    artifacts:
        paths:
          - FE/*.so
        expire_in: 60 minutes


build_Python3:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev eigen/3.3.4
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python3 BasicTools/setup.py build_ext --inplace
    artifacts:
        paths:
          - FE/*36*.so
        expire_in: 60 minutes


test_with_coverage_Python3:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - module load zset
        - export ZSET_NO_FAIL="True"
        - export PYTHONPATH=$PWD/../:$PYTHONPATH
        - mkdir -p public/coverage3
        - cd public/coverage3
        - python3 ../../Helpers/Tests.py -e ${MYPROJECT} -cl
    artifacts:
        name: "Coverage3"
        paths:
            - public/coverage3


test_with_coverage_Python2:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - export PYTHONPATH=$PWD/../:$PYTHONPATH
        - mkdir -p public/coverage2
        - cd public/coverage2
        - python ../../Helpers/Tests.py -e ${MYPROJECT} -cl
    artifacts:
        name: "Coverage2"
        paths:
            - public/coverage2


test_full_output_stop_at_first_error_Python3:
    stage: debug
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - module load zset
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f -s
    when: on_failure
    dependencies: [test_with_coverage_Python3]


test_full_output_stop_at_first_error_Python2:
    stage: debug
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - module load zset
        - module load abaqus/6.13-6
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f -s
    when: on_failure
    dependencies: [test_with_coverage_Python2]



pages:
    stage: deploy
    tags:
        - MSBasicTools
    script:
        - pwd
        - echo "Trigger TopoTools tests Pipeline"
        - "curl -k -X POST -F token=2f8781bddd013486f19b36ac3903d4 -F ref=master https://gitlab.safrantech.safran/api/v4/projects/82/trigger/pipeline"
        - echo "Trigger niROM tests Pipeline"
        - "curl -k -X POST -F token=fbf3bfaa27a78b2cdc7caf3c5780bb -F ref=master https://gitlab.safrantech.safran/api/v4/projects/138/trigger/pipeline"
        - echo "Trigger pyROMaNN tests Pipeline"
        - "curl -k -X POST -F token=ac9f98231903c38cf63bb2288a663d -F ref=master https://gitlab.safrantech.safran/api/v4/projects/199/trigger/pipeline"

    artifacts:
        name: "WebSite"
        paths:
            - public
