variables:
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'BasicTools'
    PREFIX: "/softs/python/CamLibs/BasicTools"
    ACLSCRIPT: "/softs/sttools/bin/set-acl-from-file"


stages:
    - doc
    - build
    - test
    - debug
    - deploy

build_Python3:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev eigen/3.3.4 mkl
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python3 BasicTools/setup.py build_ext --inplace
    artifacts:
        paths:
          - FE/*36*.so
        expire_in: 600 minutes

test_with_coverage_Python3:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - module load zset/8.6.9
        - export ZSET_NO_FAIL="True"
        - export PYTHONPATH=$PWD/../:$PYTHONPATH
        - mkdir -p public/coverage3
        - cd public/coverage3
        - python3 ../../Helpers/Tests.py -e ${MYPROJECT} -cl
        - grep pc_cov index.html
    coverage: '/pc_cov">([0-9]+\.?[0-9]+?%)/'        
    artifacts:
        name: "Coverage3"
        paths:
            - public/coverage3

test_full_output_stop_at_first_error_Python3:
    stage: debug
    tags:
        - MSBasicTools
    script:
        - module load PISCO/Python3Dev
        - module load zset/8.6.9
        - export ZSET_NO_FAIL="True"
        - cd ..
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f -s
    when: on_failure
    dependencies: [test_with_coverage_Python3]

pages:
    stage: deploy
    tags:
        - MSBasicTools
    script:
        - pwd
        - echo "Trigger TopoTools tests Pipeline"
        - "curl -k -X POST -F token=2f8781bddd013486f19b36ac3903d4 -F ref=master https://gitlab.safrantech.safran/api/v4/projects/82/trigger/pipeline"
        - echo "Trigger genericROM tests Pipeline"
        - "curl -k -X POST -F token=5306d10b62e5a3a0607c491a05ce6b -F ref=master https://gitlab.safrantech.safran/api/v4/projects/275/trigger/pipeline"
        - echo "Trigger niROM tests Pipeline"
        - "curl -k -X POST -F token=fbf3bfaa27a78b2cdc7caf3c5780bb -F ref=master https://gitlab.safrantech.safran/api/v4/projects/138/trigger/pipeline"
        - echo "Trigger pyROMaNN tests Pipeline"
        - "curl -k -X POST -F token=ac9f98231903c38cf63bb2288a663d -F ref=master https://gitlab.safrantech.safran/api/v4/projects/199/trigger/pipeline"
        
        

    artifacts:
        name: "WebSite"
        paths:
            - public

    only :
       - master

deploy:
  stage: deploy
  tags:
    - MSBasicTools
  script:
    - echo "Deploy..."
    - rsync -av --delete-after --cvs-exclude --exclude='.gitlab*' --omit-dir-times --no-perms . $PREFIX
    - $ACLSCRIPT $PREFIX/../.acl $PREFIX
  environment:
    name: deploy_to_softs
  only:
  - master
