variables:
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'BasicTools'

stages:
    - doc
    - build
    - test
    - coverage


doc:
    stage: doc
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl zset
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - mkdir public
        - cd docs
        - make html
        - mv _build/html ../public
    artifacts:
        paths:
            - public


build:
    stage: build
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - cd ..
        - python BasicTools/setup.py build_ext --inplace


test:
    stage: test
    tags:
        - myproject
    script:
        - module load python/2.7.12_Anaconda
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT}

testFull:
    stage: test
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f



coverage:
    stage: coverage
    tags:
        - MSBasicTools
    script:
        - module load python/2.7.12_Anaconda
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -c
        - mkdir -p public/coverage
        - mv index.html public/coverage/.
    artifacts:
        paths:
            - public
