variables:    
    GIT_SSL_NO_VERIFY: "1"
    MYPROJECT : 'BasicTools'

stages:
    - doc
    - build
    - test
    - coverage

build:
    stage: build
    tags:
        - myproject
    script:
        - module load python/2.7.12_Anaconda eigen/3.3.4 mkl
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/setup.py build_ext --inplace
   

test:
    stage: test
    tags:
        - myproject
    script:
        - module load python/2.7.12_Anaconda
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT}

testFull:
    stage: test
    tags:
        - myproject
    script:
        - module load python/2.7.12_Anaconda
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -f



coverage:
    stage: coverage
    tags:
        - myproject
    script:
        - module load python/2.7.12_Anaconda
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - python BasicTools/Helpers/Tests.py -e ${MYPROJECT} -c
