{% set data = load_setup_py_data() %}

package:
  name: "basictools"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../.

build:
  skip : True # [py==36]

  number: {{ GIT_DESCRIBE_NUMBER }}
  entry_points:
    - "MeshFileConvert = BasicTools.IO.MeshFileConverter:Main"

  skip_compile_pyc:
    "BasicToolsParaViewBridge.py"

  script_env:
    - BASICTOOLS_DISABLE_MKL
    - BASICTOOLS_USE_EIGENCYEIGEN

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - eigency
    - mkl
    - mkl-include
    - setuptools-scm
    - eigen
    - sympy
  run:
    - python
    - pyparsing
    - numpy
    - scipy
    - sympy
    - eigency=1.78
    - mkl
    - scikit-learn
    - vtk
    - meshio
    - h5py
    - pyvista [not py==36]
    - scikit-sparse [not win]

test:
  requirements:
    - coverage
  imports:
     -  BasicTools
  commands :
    - python -u -m BasicTools.Helpers.Tests -k Catalyst # [not py==36]
    - python -u -m BasicTools.Helpers.Tests -k Catalyst -k PyVistaBridge -k MeshIOBridge # [py==36]


about:
    home: {{ data['url'] }}
    license: {{ data['license'] }}
    license_file: LICENSE.txt
    license_family: BSD
    summary: {{ data['description'] }}
    description: {{ data['long_description'] }}

extra:
  recipe-maintainers:
    - felipebordeu
