{% set data = load_setup_py_data() %}

package:
  name: "basictools"
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}

source:
  path: ../../.

build:
  skip : True # [py==36 or py==37]

  number: 0
  entry_points:
    - "MeshFileConvert = BasicTools.IO.MeshFileConverter:Main"

  skip_compile_pyc:
    "BasicToolsParaViewBridge.py"

  script_env:
    - BASICTOOLS_DISABLE_MKL
    - BASICTOOLS_USE_EIGENCYEIGEN

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - numpy >=1.20
    - sympy
    - cython
    - eigency
    - mkl
    - mkl-include
    - setuptools-scm
    - eigen

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.9
    - sympy
    - vtk
    - eigency
    - mkl
    - psutil

    - scikit-sparse
    - h5py
    - meshio
    - pyvista
    - pycgns
    - networkx >=3.0 [not win]
#networkx not available on conda-forge, can be installed using pip

test:
  requirements:
    - coverage
  imports:
     -  BasicTools
  commands :
    - python -u -m BasicTools.Helpers.Tests -k Catalyst # [not py==36]


about:
    home: {{ data['url'] }}
    license: {{ data['license'] }}
    license_file: LICENSE.txt
    license_family: BSD
    summary: {{ data['description'] }}
    description: {{ data['long_description'] }}

extra:
  recipe-maintainers:
    - felipebordeu
