{% set data = load_setup_py_data() %}

package:
  name: "basictools-split"
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}

source:
      path: ../../.
build:
  number: 0

outputs:
  - name: basictools-core
    version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}
    script: build_core.sh  # [not win]
    script: bld_core.bat  # [win]
    build:
      script_env:
        - BASICTOOLS_DISABLE_MKL=0
        - BASICTOOLS_USE_EIGENCYEIGEN=0
      entry_points:
        - "MeshFileConvert = BasicTools.IO.MeshFileConverter:Main"
      skip_compile_pyc:
        "BasicToolsParaViewBridge.py"

    requirements:
      build:
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cython
      host:
        - python {{ python }}
        - numpy >=1.20

        - cython
        - sympy
        - eigency
        - mkl
        - mkl-include
        - setuptools-scm
        - eigen
        - boost-cpp
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.9
        - sympy
        - eigency
        - mkl
        - networkx >=3.0
        - scikit-sparse
    test:
      imports:
        - BasicTools
      commands:
        - python -u -m BasicTools.Helpers.Tests
  - name: "basictools-extensions"
    version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      - python
      - vtk
      - psutil
      - scikit-sparse
      - h5py
      - meshio
      - pyvista
      - networkx >=3.0
    test:
      imports:
        - psutil
        - sksparse.cholmod
        - h5py
        - meshio
        - networkx
  - name: "basictools"
    version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      run:
        - {{ pin_subpackage('basictools-core', exact=True) }}
        - {{ pin_subpackage('basictools-extensions', exact=True) }}
    test:
      imports:
        - BasicTools
      commands:
        - python -u -m BasicTools.Helpers.Tests

  - name: "basictools-devenv"
    version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - python {{ python }}
      - numpy >=1.20
      - sympy
      - cython
      - eigency
      - mkl
      - mkl-include
      - setuptools-scm
      - eigen
      - scipy >=1.9
      - eigency
      - scikit-sparse
      - h5py
      - pycgns
      - networkx >=3.0
      - boost-cpp
      - pytest
      - vtk
    test:
      imports:
        - numpy

about:
    home: {{ data['url'] }}
    license: {{ data['license'] }}
    license_file: LICENSE.txt
    license_family: BSD
    summary: {{ data['description'] }}
    description: {{ data['long_description'] }}

extra:
  recipe-maintainers:
    - felipebordeu
