
------------------------------------------------------------------------------
| YOU ARE USING ZeBuloN version 8.6.x         compiled 2016-03-04 by d582428 |
|                                             SVN revision:13609M            |
|                                                                            |
| Process Id (PID)         : 16522                                           |
| Process parent Id (PPID) : 16521                                           |
| Hostname                 : ws-crt-13                                       |
|                                                                            |
| This is a *DEVELOPMENT* version, and should be considered                  |
| as a beta version.  It is *NOT* supported by the hotline.                  |
| Use at your own risk. Contact NWNumerics or Transvalor to                  |
| get a stable release.                                                      |
|                                                                            |
|                                                                            |
| Ecole des Mines                     www.mat.ensmp.fr                       |
| NW Numerics                         www.nwnumerics.com                     |
| ONERA                               www.onera.fr                           |
------------------------------------------------------------------------------

Problem name: calcul1

============================================================
Zebulon 8.6 checking out license for fem

 checkout of license 3/1000 for product:fem
 license expires in 1725 days
============================================================

 ** SIMULATING MODE **
 File: calcul1.inp

             1.0 running 5 cycles



!!!!!!
ERROR at zSimulator/Simulator_model.c:79:
Error trying to open simulation material file: 2.0
!!!!!!

(Last system error: No such file or directory)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                     CPU time  Wall-clock
  Time CPU Total                  =         0    0.008041 (Not closed)
  Time Execution                  =         0    0.006616 (Not closed)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

