name: BasicTools3.9
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python=3.9
    - numpy
    - scipy
    - sympy
    - cython
    - vtk
    - eigency
    - mkl
    - mkl-include

    - psutil
    - eigen

#    - scikit-sparse #  [not win]
#    - matplotlib
    - pyamg
    - h5py
    - meshio
    - breathe
    - setuptools-scm
#    - pyvista  [not py==36]
    - networkx
    - sphinx_rtd_theme
#    - mpi4py

    - compilers
    - breathe
